### ISSUE TITLE
Sorry I have question.

### ISSUE THREAD

**Issue by nibgnas** [Tenyryas/lhtrpg#17]
sorry for my english skill
I don't know how to use the key value wht you wrote in Wiki

can u teach me?

I am using FVTT 10 and I try to command like this

/r @system.checks.disable.dice

but doesn't show up the result TT

質問があります
現在FVTT１０を使っていてLOG　Horizenシステムのチャットの方で命令語を使おうとしてみましたが
Wikiで書いてあるキー値を呼び出しても結果がちゃんと出ませんTT

/r @system.checks.disable.dice

こんな風にためしてみましたが・・・・
もしかして使い方が間違いましたか？

**Comment by Tenyryas** [comment]
Hi! The attribute keys values as written in the wiki are only used for Active Effects and script macros. If you want to use the values for dice rolls, you can forget the `system.` part and just type `@checks.disable.dice`. 
`@` is more or less a shortcut for `system.` when you want to use the values of your character in rolls. If you need anything else, please answer here and I'll try to help. Hope you have fun with the system nonetheless! :)

(This is a deepl translation)
こんにちは！wikiに書かれている属性キーの値は、Active Effectsとスクリプトマクロにのみ使用されます。サイコロの出目の値を使いたい場合は、`system.`の部分を忘れて、`@checks.disable.dice`とタイプしてください。
`@` は多かれ少なかれ、自分のキャラクターの値をロールに使いたいときの `system.` のショートカットになっています。もし他に何か必要なものがあれば、ここで答えてください。それでもこのシステムを楽しんでいただけると幸いです。:)

**Comment by nibgnas** [comment]
ダイスロール教えていただいた値で試してみるとちゃんとチャットで動きますね！ありがとうございます！

＠の方がSystemの代わりだとは・・・
まだEffectの使い方がわからなく困っていますｗ
Temporary　EffectとかPassive　EffctとかInactive Effectのそれぞれの違いやAddを使ってどうやって上のキーを使うのかとか・・・（涙）

まだ使って日が浅いですが、頑張ってみます！
（多分知らないところだらけで今後も質問連続になると思いますが・・・大丈夫ですか？）

もしこれからの投稿する時日本語で質問残してもいいですか？
自分も日本語の方が楽なので・・・（涙）

本当早い返事ありがとうございます！
すごく助かりました：）

**Comment by Tenyryas** [comment]
Aye, don't worry too much about writing your questions in japanese, unless it's very technical I'm sure DeepL will be able to help me understand you.

As for Active Effects... Temporary Effects are Effects that have a duration. They're mostly used in battles, for temporary buffs and debuffs. Passive Effects are bonuses that are always active, like for the 狼牙族 racial skill 狼の体術  , which is a permanent +4 STR bonus. Inactive Effects are disabled effects. Keep in mind that due to FVTT limitations, you can't add Active Effects on an item or skill that is already on a character sheet, you need to add them before adding the skill or item to a character.

For creating an Active Effect, just click on Add, you can then modify attributes and all using the keys I've written in the wiki page, like this.
![image](https://user-images.githubusercontent.com/61804473/191076428-7e72e159-a880-4b4b-b68e-8ff92401f60c.png)


日本語で質問を書いてもあまり気にしないでください。よほど専門的なことでない限り、DeepLがあなたのことを理解する手助けをしてくれると思います。

アクティブ効果についてですが... 一時的な効果は、持続時間がある効果です。バトルで一時的なバフやデバフとして使われることが多い。受動的効果とは、常に有効なボーナスです。例えば、狼牙族の種族スキルである狼の体術は、永久に+4 STRのボーナスを得ることができます。非活性効果は無効になる効果です。FVTTの制限により、キャラクターシートに既にあるアイテムやスキルにアクティブ効果を追加することはできませんので、スキルやアイテムをキャラクターに追加する前に追加する必要があることに注意してください。

Active Effectの作成は、Addをクリックするだけで、あとはWikiページに書いてあるキーで属性などを変更できます。
(DeepL translation, sorry if it's not clear)

**Comment by nibgnas** [comment]
oh...sorry about that.
I thought u are japanese :) cuz you're japanese like natural.

Thanks for example.
I'll reserch what you taught me.

you're really nice developer!!!!!!
thanks for you're kindess
(I want to wirte more my applicate. but my english skill is not good enough.TT)

**Comment by Tenyryas** [comment]
Aye, I'm not japanese, I'm french. :)
I can thank DeepL for my excellent japanese, lol.
Do not hesitate about asking for more help in the future if needed. You can either open another ticket on Github or write to me directly on Discord at `Kyane#8654` if needed.

はい、私は日本人ではなく、フランス人です。:)
私の日本語が上手なのは、DeepLさんのおかげです(笑)。
もし必要なら、今後も遠慮なく助けを求めてください。Githubで別のチケットを開くか、必要ならDiscordの`Kyane#8654`で直接私に書き込んでください。
